global:
  scrape_interval: 10s
scrape_configs:
  - job_name: 'api-gateway-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway-service-app:8111']
